image: node

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - mkdir min
          - npm install uglify-js -g
          - npm install csso-cli -g
          - uglifyjs lightbox.js -m -o min/lightbox.min.js
          - csso lightbox.css -o min/lightbox.min.css
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-1'
              S3_BUCKET: 'lightbox-templates'
              LOCAL_PATH: 'min'
              
          # - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
          #   variables:
          #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_DMC
          #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_DMC
          #     AWS_DEFAULT_REGION: 'us-east-1'              
          #     DISTRIBUTION_ID: 'ECCA3RUK90SDI'